# Generated by Django 6.0.4 on 2026-05-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('age', models.IntegerField(max_length=3, verbose_name='Возраст')),
                ('on_vacation', models.BooleanField(default=False, verbose_name='В отпуске')),
                ('_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('inn', models.IntegerField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.IntegerField(max_length=13, verbose_name='ОГРН')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя ребенка')),
                ('age', models.IntegerField(max_length=3, verbose_name='Возраст')),
                ('school_number', models.IntegerField(max_length=12, verbose_name='Номер школы')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.employee', verbose_name='Родитель')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование отдела')),
                ('base_salary_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Переопределение базовой ставки')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hr.enterprise', verbose_name='Предприятие')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование должности')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая ставка')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.enterprise', verbose_name='Предприятие')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr.position', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='PositionDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.position')),
            ],
            options={
                'unique_together': {('position', 'department')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='positions', through='hr.PositionDepartment', to='hr.department'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешняя компания')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Коэффициент ставки')),
                ('job_type', models.CharField(choices=[('main', 'Основное место работы'), ('internal', 'Внутреннее совместительство'), ('external', 'Внешнее совместительство')], max_length=20, verbose_name='Тип занятости')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное место работы')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hr.department', verbose_name='Отдел')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hr.employee', verbose_name='Сотрудник')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('job_type', 'main')), fields=('employee', 'job_type'), name='unique_main_job')],
            },
        ),
    ]
